version = 0.1
[default.deploy.parameters]
stack_name = "ms-mail-delivery"
resolve_s3 = true
s3_prefix = "ms-mail-delivery"
region = "us-west-2"
confirm_changeset = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
image_repositories = []
